apiVersion: batch/v1
kind: Job
metadata:
  name: vltge-crtfct-job
spec:
  template:
    spec:
      containers:
      - name: vltge-crtfct-job
        image: yash5090/vltge-crtfct:latest
        ports:
        - containerPort: 3000
      restartPolicy: OnFailure
