apiVersion: apps/v1
kind: Deployment
metadata:
  name: vltge-crtfct-deployment
spec:
  replicas: 6 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: vltge-crtfct
  template:
    metadata:
      labels:
        app: vltge-crtfct
    spec:
      containers:
        - name: vltge-crtfct
          image: yash5090/vltge-crtfct:latest # Replace with the actual image tag
          ports:
            - containerPort: 3000 # Replace with the port your Tetris game listens on
